In [1]:
# test for coordinate system transform(construct the thumb finger base plane normal vector)
# the mujoco world coordinate system(x:right/y:forward/z:up)

import numpy as np


vector1 = np.array([0,0,1]) #the thumb plane normal vector at the condition that the thumb joint0 rotate axis is y

# method 1:(rotate target coordinate around reference coodinate by the regular sequence x, y and z axis)
# gamma = np.pi/4 #for x axis
# beta = -np.pi/4 #for y axis
# alpha = -np.pi/4 #for z axis

# the sequence of rotation is x, y and z（at the mujoco coordinate system: x:right,y:backward,z:down）
# trans = np.matrix([[np.cos(alpha)*np.cos(beta), np.cos(alpha)*np.sin(beta)*np.sin(gamma)-np.sin(alpha)*np.cos(gamma), np.cos(alpha)*np.sin(beta)*np.cos(gamma)+np.sin(alpha)*np.sin(gamma)], [np.sin(alpha)*np.cos(beta), np.sin(alpha)*np.sin(beta)*np.sin(gamma)+np.cos(alpha)*np.cos(gamma), np.sin(alpha)*np.sin(beta)*np.cos(gamma)-np.cos(alpha)*np.sin(gamma)], [-np.sin(beta), np.cos(beta)*np.sin(gamma), np.cos(beta)*np.cos(gamma)]])
# print(trans)

# method 2:(rotate target coordinate around itself by the regular sequence z, y and x axis)
alpha = np.pi/3 #for x axis
beta = 0.0 #for y axis
gamma = np.pi/4 #for z axis

Rx = np.matrix([[1, 0, 0], [0, np.cos(alpha), -np.sin(alpha)], [0, np.sin(alpha), np.cos(alpha)]])
Ry = np.matrix([[np.cos(beta), 0, np.sin(beta)], [0, 1, 0], [-np.sin(beta), 0, np.cos(beta)]])
Rz = np.matrix([[np.cos(gamma), -np.sin(gamma), 0], [np.sin(gamma), np.cos(gamma), 0],[0, 0, 1]])

# euler rotate(regular rotate sequence: zyx)
transform = Rz * Ry * Rx
print(transform)

vector2 = transform * vector1.reshape(3,1) #calc the new plane normal vector in the new coordinate（the joint rotate axis is still y）
print(vector2)



[[ 0.70710678 -0.35355339  0.61237244]
 [ 0.70710678  0.35355339 -0.61237244]
 [ 0.          0.8660254   0.5       ]]
[[ 0.61237244]
 [-0.61237244]
 [ 0.5       ]]
